spring.application.name=security

logging.level.org.springframework.security=DEBUG

spring.datasource.url=jdbc:mysql://localhost/sprsecurity
spring.datasource.username=root
spring.datasource.password=1234

jwt.secret=6pBg8pHqMl3S59GyXtLTFe+zC/k5d2NH0qOv6CuYl8U3CWcE5L7q6CzzufNzA8ctT2tsd74m0uK3Kf5mKZ1IjA==
jwt.accessExpiration=3600


